package TimelineApplication;
import static TimelineApplication.EditEventNum.editPosNum;
import static TimelineApplication.Maintimeline.addBtnClicked;
import static TimelineApplication.Maintimeline.editBtnClicked;
import static TimelineApplication.Maintimeline.eventInformationList;
import static TimelineApplication.Maintimeline.numOfEvents;
import static TimelineApplication.Maintimeline.updateScreen;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AddEvent extends javax.swing.JFrame {

    public static String oldColorR;
    public static String oldColorG;
    public static String oldColorB;
    public static int oldPosition;
    
    public AddEvent() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        middlePanel = new javax.swing.JPanel();
        editImage = new javax.swing.JLabel();
        positionPanel = new javax.swing.JPanel();
        positionLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        descriptionPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        imgUrlPanel = new javax.swing.JPanel();
        imageUrlLabel = new javax.swing.JLabel();
        imgUrlPanel1 = new javax.swing.JPanel();
        imageUrlLabel1 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescriptionTextField = new javax.swing.JTextArea();
        EventPositionTextField = new javax.swing.JTextField();
        TimeTextField = new javax.swing.JTextField();
        EventNameTextField = new javax.swing.JTextField();
        ImageUrlTextField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        positionLabel1 = new javax.swing.JLabel();
        SearchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        sidePanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setMinimumSize(new java.awt.Dimension(430, 535));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        middlePanel.setBackground(new java.awt.Color(0, 91, 229));
        middlePanel.setMaximumSize(new java.awt.Dimension(500, 535));
        middlePanel.setMinimumSize(new java.awt.Dimension(500, 535));
        middlePanel.setPreferredSize(new java.awt.Dimension(147, 535));

        editImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/AddIconHover.png"))); // NOI18N

        positionPanel.setBackground(new java.awt.Color(0, 51, 153));
        positionPanel.setForeground(new java.awt.Color(255, 255, 255));
        positionPanel.setToolTipText("");
        positionPanel.setMaximumSize(new java.awt.Dimension(147, 47));
        positionPanel.setMinimumSize(new java.awt.Dimension(147, 47));
        positionPanel.setLayout(new java.awt.GridBagLayout());

        positionLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(255, 255, 255));
        positionLabel.setText("Position");
        positionPanel.add(positionLabel, new java.awt.GridBagConstraints());

        titlePanel.setBackground(new java.awt.Color(0, 51, 153));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));
        titlePanel.setToolTipText("");
        titlePanel.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 52, 13, 62);
        titlePanel.add(titleLabel, gridBagConstraints);

        datePanel.setBackground(new java.awt.Color(0, 51, 153));
        datePanel.setForeground(new java.awt.Color(255, 255, 255));
        datePanel.setToolTipText("");
        datePanel.setLayout(new java.awt.GridBagLayout());

        dateLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 52, 13, 60);
        datePanel.add(dateLabel, gridBagConstraints);

        descriptionPanel.setBackground(new java.awt.Color(0, 51, 153));
        descriptionPanel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionPanel.setToolTipText("");
        descriptionPanel.setMaximumSize(new java.awt.Dimension(128, 98));
        descriptionPanel.setMinimumSize(new java.awt.Dimension(128, 98));
        descriptionPanel.setLayout(new java.awt.GridBagLayout());

        descriptionLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 30, 39, 31);
        descriptionPanel.add(descriptionLabel, gridBagConstraints);

        imgUrlPanel.setBackground(new java.awt.Color(0, 51, 153));
        imgUrlPanel.setForeground(new java.awt.Color(255, 255, 255));
        imgUrlPanel.setToolTipText("");
        imgUrlPanel.setLayout(new java.awt.GridBagLayout());

        imageUrlLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        imageUrlLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageUrlLabel.setText("Image URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 35, 13, 32);
        imgUrlPanel.add(imageUrlLabel, gridBagConstraints);

        imgUrlPanel1.setBackground(new java.awt.Color(255, 102, 0));
        imgUrlPanel1.setForeground(new java.awt.Color(255, 255, 255));
        imgUrlPanel1.setToolTipText("");
        imgUrlPanel1.setLayout(new java.awt.GridBagLayout());

        imageUrlLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        imageUrlLabel1.setForeground(new java.awt.Color(255, 255, 255));
        imageUrlLabel1.setText("Google Search");
        imgUrlPanel1.add(imageUrlLabel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middlePanelLayout.createSequentialGroup()
                .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(middlePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(editImage))
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(imgUrlPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgUrlPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(middlePanelLayout.createSequentialGroup()
                .addComponent(positionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middlePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(editImage)
                .addGap(29, 29, 29)
                .addComponent(positionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(imgUrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgUrlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(middlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 0, -1, 580));

        rightPanel.setBackground(new java.awt.Color(244, 249, 255));
        rightPanel.setMaximumSize(new java.awt.Dimension(500, 535));
        rightPanel.setMinimumSize(new java.awt.Dimension(500, 535));
        rightPanel.setPreferredSize(new java.awt.Dimension(1185, 535));
        rightPanel.setLayout(null);

        DescriptionTextField.setColumns(20);
        DescriptionTextField.setLineWrap(true);
        DescriptionTextField.setRows(5);
        DescriptionTextField.setToolTipText("");
        DescriptionTextField.setWrapStyleWord(true);
        DescriptionTextField.setBorder(null);
        jScrollPane2.setViewportView(DescriptionTextField);

        rightPanel.add(jScrollPane2);
        jScrollPane2.setBounds(10, 288, 200, 110);

        EventPositionTextField.setMinimumSize(new java.awt.Dimension(200, 47));
        EventPositionTextField.setPreferredSize(new java.awt.Dimension(200, 47));
        EventPositionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventPositionTextFieldActionPerformed(evt);
            }
        });
        rightPanel.add(EventPositionTextField);
        EventPositionTextField.setBounds(10, 132, 200, 47);

        TimeTextField.setMinimumSize(new java.awt.Dimension(200, 47));
        TimeTextField.setPreferredSize(new java.awt.Dimension(200, 47));
        TimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeTextFieldActionPerformed(evt);
            }
        });
        rightPanel.add(TimeTextField);
        TimeTextField.setBounds(10, 240, 200, 47);

        EventNameTextField.setMinimumSize(new java.awt.Dimension(200, 47));
        EventNameTextField.setPreferredSize(new java.awt.Dimension(200, 47));
        EventNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventNameTextFieldActionPerformed(evt);
            }
        });
        rightPanel.add(EventNameTextField);
        EventNameTextField.setBounds(10, 186, 200, 47);

        ImageUrlTextField.setMinimumSize(new java.awt.Dimension(6, 47));
        ImageUrlTextField.setPreferredSize(new java.awt.Dimension(6, 47));
        ImageUrlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageUrlTextFieldActionPerformed(evt);
            }
        });
        rightPanel.add(ImageUrlTextField);
        ImageUrlTextField.setBounds(10, 400, 200, 47);

        addBtn.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 13)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/nextBtnNonHover.png"))); // NOI18N
        addBtn.setContentAreaFilled(false);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/nextBtnHover.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        rightPanel.add(addBtn);
        addBtn.setBounds(10, 500, 50, 49);

        CancelBtn.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 13)); // NOI18N
        CancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/cancelBtnNonHover.png"))); // NOI18N
        CancelBtn.setBorderPainted(false);
        CancelBtn.setContentAreaFilled(false);
        CancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/cancelBtnHover.png"))); // NOI18N
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        rightPanel.add(CancelBtn);
        CancelBtn.setBounds(160, 500, 50, 49);

        positionLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 80)); // NOI18N
        positionLabel1.setText("Add");
        rightPanel.add(positionLabel1);
        positionLabel1.setBounds(30, 20, 145, 92);
        rightPanel.add(SearchInput);
        SearchInput.setBounds(10, 453, 140, 31);

        searchBtn.setBackground(new java.awt.Color(0, 255, 153));
        searchBtn.setText("✓");
        searchBtn.setBorderPainted(false);
        searchBtn.setContentAreaFilled(false);
        searchBtn.setOpaque(true);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        rightPanel.add(searchBtn);
        searchBtn.setBounds(160, 453, 50, 31);

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 240, 580));

        sidePanel1.setBackground(new java.awt.Color(244, 249, 255));
        sidePanel1.setMaximumSize(new java.awt.Dimension(500, 535));
        sidePanel1.setMinimumSize(new java.awt.Dimension(500, 535));

        javax.swing.GroupLayout sidePanel1Layout = new javax.swing.GroupLayout(sidePanel1);
        sidePanel1.setLayout(sidePanel1Layout);
        sidePanel1Layout.setHorizontalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        sidePanel1Layout.setVerticalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(sidePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventPositionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventPositionTextFieldActionPerformed

    }//GEN-LAST:event_EventPositionTextFieldActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        addBtnClicked = false;
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int eventPos = Integer.parseInt(EventPositionTextField.getText());
        String eventName = EventNameTextField.getText();
        String eventDate = TimeTextField.getText();
        String eventDesc = DescriptionTextField.getText();
        String eventImg = ImageUrlTextField.getText();
           
           
           
        if(numOfEvents < 20){
            if(eventPos > 0 && eventPos <= (numOfEvents + 1)){
                eventInformationList.add(eventPos, new ArrayList<String>()); //inserting a new sublist to then add the new event info into
                eventInformationList.get(eventPos).add(eventName);
                eventInformationList.get(eventPos).add(eventDate); 
                eventInformationList.get(eventPos).add(eventDesc);
                eventInformationList.get(eventPos).add(eventImg);
                eventInformationList.get(eventPos).add("0");
                eventInformationList.get(eventPos).add("0");
                eventInformationList.get(eventPos).add("0");
                numOfEvents +=1;
                updateScreen(numOfEvents);
            }
            else{
                JOptionPane.showMessageDialog(null, "That is an invalid event position!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "You have reached the maximum number of events!");
        }
           
        addBtnClicked = false;
        this.dispose();

    }//GEN-LAST:event_addBtnActionPerformed

    private void ImageUrlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageUrlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageUrlTextFieldActionPerformed

    private void EventNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventNameTextFieldActionPerformed

    private void TimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeTextFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchedWord = SearchInput.getText().replace(" ","");
        try{
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("https://www.google.com/search?hl=en&q=images+for+"+searchedWord+"&btnG=Google+Search"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erorr occured. Possibly no internet connection.");
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextArea DescriptionTextField;
    private javax.swing.JTextField EventNameTextField;
    public static javax.swing.JTextField EventPositionTextField;
    private javax.swing.JTextField ImageUrlTextField;
    private javax.swing.JTextField SearchInput;
    private javax.swing.JTextField TimeTextField;
    public static javax.swing.JButton addBtn;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JLabel editImage;
    private javax.swing.JLabel imageUrlLabel;
    private javax.swing.JLabel imageUrlLabel1;
    private javax.swing.JPanel imgUrlPanel;
    private javax.swing.JPanel imgUrlPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel positionLabel1;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel sidePanel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
