/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TimelineApplication;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author S199841769
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Start() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TimelineBuilderLabel = new javax.swing.JLabel();
        sloganLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        TimelineBuilderLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 110)); // NOI18N
        TimelineBuilderLabel.setText("Timeless");
        getContentPane().add(TimelineBuilderLabel);
        TimelineBuilderLabel.setBounds(430, 150, 360, 90);

        sloganLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        sloganLabel.setText("Create the future, relive the past");
        getContentPane().add(sloganLabel);
        sloganLabel.setBounds(510, 250, 310, 21);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/logo.png"))); // NOI18N
        getContentPane().add(logoLabel);
        logoLabel.setBounds(-30, 20, 680, 600);

        Start.setBackground(new java.awt.Color(238, 119, 25));
        Start.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Start.setForeground(new java.awt.Color(0, 51, 255));
        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/startArrowNonHover.png"))); // NOI18N
        Start.setToolTipText("");
        Start.setBorderPainted(false);
        Start.setContentAreaFilled(false);
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/startArrowHover.png"))); // NOI18N
        Start.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/startArrowHover.png"))); // NOI18N
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        getContentPane().add(Start);
        Start.setBounds(610, 350, 230, 159);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimelineApplication/blueWallpaper.jpg"))); // NOI18N
        backgroundLabel.setText("jLabel1");
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1030, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        Maintimeline mainscreen = new Maintimeline();
        mainscreen.setVisible(true);
        super.dispose();

        Start.setBackground(Color.blue);

    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Start;
    private javax.swing.JLabel TimelineBuilderLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel sloganLabel;
    // End of variables declaration//GEN-END:variables
}
